/**
 * Dota 2 Hero ID to localized display name mapping.
 * Sourced from official Dota 2 definitions / OpenDota hero constants.
 */
export const DOTA2_HEROES: Record<number, string> = {
  1: 'Anti-Mage',
  2: 'Axe',
  3: 'Bane',
  4: 'Bloodseeker',
  5: 'Crystal Maiden',
  6: 'Drow Ranger',
  7: 'Earthshaker',
  8: 'Juggernaut',
  9: 'Mirana',
  10: 'Morphling',
  11: 'Shadow Fiend',
  12: 'Phantom Lancer',
  13: 'Puck',
  14: 'Pudge',
  15: 'Razor',
  16: 'Sand King',
  17: 'Storm Spirit',
  18: 'Sven',
  19: 'Tiny',
  20: 'Vengeful Spirit',
  21: 'Windranger',
  22: 'Zeus',
  23: 'Kunkka',
  25: 'Lina',
  26: 'Lion',
  27: 'Shadow Shaman',
  28: 'Slardar',
  29: 'Tidehunter',
  30: 'Witch Doctor',
  31: 'Lich',
  32: 'Riki',
  33: 'Enigma',
  34: 'Tinker',
  35: 'Sniper',
  36: 'Necrophos',
  37: 'Warlock',
  38: 'Beastmaster',
  39: 'Queen of Pain',
  40: 'Venomancer',
  41: 'Faceless Void',
  42: 'Wraith King',
  43: 'Death Prophet',
  44: 'Phantom Assassin',
  45: 'Pugna',
  46: 'Templar Assassin',
  47: 'Viper',
  48: 'Luna',
  49: 'Dragon Knight',
  50: 'Dazzle',
  51: 'Clockwerk',
  52: 'Leshrac',
  53: "Nature's Prophet",
  54: 'Lifestealer',
  55: 'Dark Seer',
  56: 'Clinkz',
  57: 'Omniknight',
  58: 'Enchantress',
  59: 'Huskar',
  60: 'Night Stalker',
  61: 'Broodmother',
  62: 'Bounty Hunter',
  63: 'Weaver',
  64: 'Jakiro',
  65: 'Batrider',
  66: 'Chen',
  67: 'Spectre',
  68: 'Ancient Apparition',
  69: 'Doom',
  70: 'Ursa',
  71: 'Spirit Breaker',
  72: 'Gyrocopter',
  73: 'Alchemist',
  74: 'Invoker',
  75: 'Silencer',
  76: 'Outworld Destroyer',
  77: 'Lycan',
  78: 'Brewmaster',
  79: 'Shadow Demon',
  80: 'Lone Druid',
  81: 'Chaos Knight',
  82: 'Meepo',
  83: 'Treant Protector',
  84: 'Ogre Magi',
  85: 'Undying',
  86: 'Rubick',
  87: 'Disruptor',
  88: 'Nyx Assassin',
  89: 'Naga Siren',
  90: 'Keeper of the Light',
  91: 'Io',
  92: 'Visage',
  93: 'Slark',
  94: 'Medusa',
  95: 'Troll Warlord',
  96: 'Centaur Warrunner',
  97: 'Magnus',
  98: 'Timbersaw',
  99: 'Bristleback',
  100: 'Tusk',
  101: 'Skywrath Mage',
  102: 'Abaddon',
  103: 'Elder Titan',
  104: 'Legion Commander',
  105: 'Techies',
  106: 'Ember Spirit',
  107: 'Earth Spirit',
  108: 'Underlord',
  109: 'Terrorblade',
  110: 'Phoenix',
  111: 'Oracle',
  112: 'Winter Wyvern',
  113: 'Arc Warden',
  114: 'Monkey King',
  119: 'Dark Willow',
  120: 'Pangolier',
  121: 'Grimstroke',
  123: 'Hoodwink',
  126: 'Void Spirit',
  128: 'Snapfire',
  129: 'Mars',
  131: 'Ringmaster',
  135: 'Dawnbreaker',
  136: 'Marci',
  137: 'Primal Beast',
  138: 'Muerta',
  145: 'Kez',
};

export function getHeroNameById(heroId: number | string | undefined | null): string {
  if (!heroId) return 'Unknown';
  const idNum = typeof heroId === 'string' ? parseInt(heroId, 10) : heroId;
  if (isNaN(idNum) || idNum <= 0) return 'Unknown';
  return DOTA2_HEROES[idNum] || `Hero ${idNum}`;
}

export const HERO_ROLE_MAP: Record<string, string> = {
  // Supports
  'Snapfire': 'Support',
  'Crystal Maiden': 'Support',
  'Lion': 'Support',
  'Shadow Shaman': 'Support',
  'Witch Doctor': 'Support',
  'Lich': 'Support',
  'Bane': 'Support',
  'Dazzle': 'Support',
  'Jakiro': 'Support',
  'Rubick': 'Support',
  'Disruptor': 'Support',
  'Oracle': 'Support',
  'Winter Wyvern': 'Support',
  'Grimstroke': 'Support',
  'Io': 'Support',
  'Chen': 'Support',
  'Ancient Apparition': 'Support',
  'Treant Protector': 'Support',
  'Ogre Magi': 'Support',
  'Undying': 'Support',
  'Shadow Demon': 'Support',
  'Nyx Assassin': 'Support',
  'Skywrath Mage': 'Support',
  'Keeper of the Light': 'Support',
  'Dark Willow': 'Support',
  'Hoodwink': 'Support',
  'Ringmaster': 'Support',
  'Marci': 'Support',
  // Offlaners
  'Slardar': 'Offlane',
  'Axe': 'Offlane',
  'Centaur Warrunner': 'Offlane',
  'Tidehunter': 'Offlane',
  'Bristleback': 'Offlane',
  'Mars': 'Offlane',
  'Timbersaw': 'Offlane',
  'Underlord': 'Offlane',
  'Dark Seer': 'Offlane',
  'Beastmaster': 'Offlane',
  'Night Stalker': 'Offlane',
  'Doom': 'Offlane',
  'Primal Beast': 'Offlane',
  'Dawnbreaker': 'Offlane',
  'Clockwerk': 'Offlane',
  'Magnus': 'Offlane',
  'Spirit Breaker': 'Offlane',
  'Pangolier': 'Offlane',
  // Midlaners
  'Death Prophet': 'Mid',
  'Ember Spirit': 'Mid',
  'Dragon Knight': 'Mid',
  'Storm Spirit': 'Mid',
  'Void Spirit': 'Mid',
  'Puck': 'Mid',
  'Queen of Pain': 'Mid',
  'Invoker': 'Mid',
  'Lina': 'Mid',
  'Shadow Fiend': 'Mid',
  'Tinker': 'Mid',
  'Leshrac': 'Mid',
  'Outworld Destroyer': 'Mid',
  'Zeus': 'Mid',
  'Kunkka': 'Mid',
  'Batrider': 'Mid',
  // Carries
  'Lone Druid': 'Carry',
  'Alchemist': 'Carry',
  'Medusa': 'Carry',
  'Monkey King': 'Carry',
  'Anti-Mage': 'Carry',
  'Phantom Assassin': 'Carry',
  'Faceless Void': 'Carry',
  'Juggernaut': 'Carry',
  'Morphling': 'Carry',
  'Phantom Lancer': 'Carry',
  'Spectre': 'Carry',
  'Sven': 'Carry',
  'Terrorblade': 'Carry',
  'Drow Ranger': 'Carry',
  'Luna': 'Carry',
  'Ursa': 'Carry',
  'Slark': 'Carry',
  'Troll Warlord': 'Carry',
  'Lifestealer': 'Carry',
  'Wraith King': 'Carry',
  'Bloodseeker': 'Carry',
  'Weaver': 'Carry',
  'Clinkz': 'Carry',
  'Muerta': 'Carry',
};

export function getRoleByHeroName(heroName: string | undefined | null): string | null {
  if (!heroName) return null;
  return HERO_ROLE_MAP[heroName.trim()] || null;
}
